# Generated by Django 4.0.2 on 2022-02-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('fk_dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo_reparacion', to='common.dispositivo')),
                ('fk_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_reparaciones', to='common.persona')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_reparaciones', to='common.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fk_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparacion_obs', to='registro.reparacion')),
            ],
        ),
    ]
