# Generated by Django 4.0.2 on 2022-02-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='fk_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_reparaciones', to='common.producto'),
        ),
    ]
