# Generated by Django 4.0.2 on 2022-02-21 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0002_alter_reparacion_fk_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_repraciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
